package enums;

public enum BindType { CIRCLE_CENTER, CIRCLE_PERIPHER, CIRCLEARC_CENTER, CIRCLEARC_START, CIRCLEARC_END, CIRCLEARC_RADIUS, LINE_START, LINE_CENTER, LINE_END, POLY_POINT, POLY_CENTER, OVAL_CENTER, OVAL_P1, OVAL_P2, OVAL_PERIPHER; }
